name: Check Compatibility

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run check_compatibility()
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python legalzard/licencepy.py check_compatibility





# name: Check compatibility
# on:
#   package_install:
#     branches:
#       - main
#     paths:
#       - .github/workflows/check_compatibility.yaml
#       - src/create_licence.py
# jobs:
#   check-compatibility:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-python@v2
#         with:
#           python-version: 3.8
#       - run: |
#           python src/create_licence.py
#           if __name__ == "__main__":
#             check_compatibility()
